add_parcel:
  fields:
    device_id:
      description: "The device to target."
      example: "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4"
      required: true
      selector:
        device:
          integration: parcelapp
    parcel_name:
      example: "My Parcel"
      required: true
      selector:
        text:
    tracking_number:
      example: "1234567890"
      required: true
      selector:
        text:
    courier:
      example: "ups"
      required: true
      selector:
        text:

delete_parcel:
  fields:
    device_id:
      description: "The device to target."
      example: "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4"
      required: true
      selector:
        device:
          integration: parcelapp
    tracking_number:
      example: "1234567890"
      required: true
      selector:
        text:
    type:
      example: "package"
      required: true
      selector:
        text:

edit_parcel:
  fields:
    device_id:
      description: "The device to target."
      example: "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4"
      required: true
      selector:
        device:
          integration: parcelapp
    parcel_name:
      example: "Updated Parcel Name"
      required: true
      selector:
        text:
    tracking_number:
      example: "1234567890"
      required: true
      selector:
        text:
    courier:
      example: "fedex"
      required: true
      selector:
        text:
    old_number:
      example: "1234567890"
      required: true
      selector:
        text:
    old_type:
      example: "fedex"
      required: true
      selector:
        text: